# Generated by Django 4.1.7 on 2023-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.IntegerField()),
                ('statement_name', models.CharField(max_length=200)),
                ('statement_img', models.ImageField(upload_to='')),
                ('statement_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
